debug

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -51,10 +51,15 @@ jobs:
         run: |
           echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
           hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
+          ls -l ./public 
       - name: Upload artifact
-        uses: actions/upload-pages-artifact@v3
+        uses: actions/upload-pages-artifact@v4
         with:
           path: ./public
+      - name: Debug artifact upload
+        run: |
+          echo "Checking if ./public exists"
+          ls -l ./public || echo "Public folder not found!"
 
   # Deploy website to GitHub Pages hosting
   deploy:
@@ -65,6 +70,9 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
+      - name: Debug artifact list
+        run: ls -l /home/runner/work/_temp
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v2
+
